name: build and test pull request

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies for backend
        working-directory: ${{ github.workspace }}/api
        run: yarn install
      
      - name: Test the backend
        working-directory: ${{ github.workspace }}/api
        run: yarn test

      - name: Run ESLint and report with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          filter_mode: file
          workdir: ./api

      - name: Install dependencies for frontend
        working-directory: ${{ github.workspace }}/web
        run: yarn install

      - name: Test the frontend
        working-directory: ${{ github.workspace }}/web
        run: yarn test
